[package]
name = "media_core"
version = "0.1.0"
authors = ["royeeliu <royeeliu@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[lib]
name = "MediaCore"
crate-type = ["cdylib"]